apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewandrating-service-app-metadata-name
  labels:
    app: reviewandrating-service-app-metadata-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewandrating-service-app
  template:
    metadata:
      labels:
        app: reviewandrating-service-app
    spec:
      containers:
      - name: reviewandrating-service-app-container
        image: seemapawar/reviewandrating-service:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080