apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app-metadata-name
  labels:
    app: user-service-app-metadata-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app-container
        image: seemapawar/user-service:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9002